server:
  port: 0
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/finflow_auth?createDatabaseIfNotExist=true
    username: root
    password: tiger
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URI:http://localhost:9411/api/v2/spans}
