version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: finflow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      # Databases will be created automatically via JDBC connection strings if createDatabaseIfNotExist=true is used,
      # but we can optionally define a starting DB here.
      MYSQL_DATABASE: finflow_auth
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
